# Generated by Django 4.2.6 on 2023-10-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('request_orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedi',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section', verbose_name='Section ID'),
        ),
        migrations.AddField(
            model_name='uploadedi',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier', verbose_name='Supplier ID'),
        ),
        migrations.AddField(
            model_name='uploadedi',
            name='upload_by_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Upload By ID'),
        ),
        migrations.AddField(
            model_name='requestorderdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product ID'),
        ),
        migrations.AddField(
            model_name='requestorderdetail',
            name='request_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Request By ID'),
        ),
        migrations.AddField(
            model_name='requestorderdetail',
            name='request_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_orders.requestorder', verbose_name='Request ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='Book ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='edi_file_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='request_orders.uploadedi', verbose_name='EDI File ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='product_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgroup', verbose_name='Model ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='ro_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Request By ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section', verbose_name='Section ID'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supplier', verbose_name='Supplier ID'),
        ),
        migrations.AddField(
            model_name='approverequestorder',
            name='request_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Request By ID'),
        ),
        migrations.AddField(
            model_name='approverequestorder',
            name='request_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_orders.requestorder', verbose_name='Request ID'),
        ),
    ]
