# Generated by Django 4.2.6 on 2023-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverequestorder',
            name='request_status',
            field=models.CharField(choices=[('0', 'In Progress'), ('1', 'Approve'), ('2', 'Success'), ('3', 'Reject')], default='0', max_length=1, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='ro_status',
            field=models.CharField(choices=[('0', 'In Progress'), ('1', 'Approve'), ('2', 'Success'), ('3', 'Reject')], default='0', max_length=1, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='requestorderdetail',
            name='request_status',
            field=models.CharField(choices=[('0', 'In Progress'), ('1', 'Approve'), ('2', 'Success'), ('3', 'Reject')], default='0', max_length=1, verbose_name='Request Status'),
        ),
    ]
