# Generated by Django 4.2.6 on 2023-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementuser',
            name='supplier_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='SetSupplier', to='users.supplier', verbose_name='Supplier ID'),
        ),
    ]
