--Query OrderH
--@set orderID = ('WUJA3hyW', '_6nUONMg')
--select @orderID

select 
FCDATASER, FCSKID, FCLUPDAPP, FCRFTYPE, FCREFTYPE, FCCORP, FCBRANCH, FCDEPT, FCSECT, FCJOB, FCSTEP, FDDATE, FDDUEDATE, FDRECEDATE, FCBOOK, FCCODE, FCREFNO, FNAMT, FNAMT2, 
                         FCVATISOUT, FCVATTYPE, FNVATRATE, FNVATAMT, FCCOOR, FNCREDTERM, FCCREATEBY, FCCORRECTB, FCEAFTERR, FTDATETIME, FCPROJ, FNAMTKE, FNVATAMTKE, FNXRATE, FCAPPROVEB, FCDELICOOR, FDAPPROVE, 
                         FTLASTUPD, FDREQDATE, FCCREATEAP, FCISPDPART
from ORDERH where FCSKID in :orderID

--Query ORDERI
SELECT  FCDATASER, FCSKID, FCLUPDAPP, FCSTEP, FCCORP, FCBRANCH, FCDEPT, FCSECT, FCJOB, FCORDERH, FDDATE, FCCOOR, FCREFPDTYP, FCREFTYPE, FCPRODTYPE, FCSHOWCOMP, FCPROD, FCUM, FCUMSTD, 
                         FNUMQTY, FNQTY, FNBACKQTY, FNPRICE, FCSEQ, FCVATISOUT, FCVATTYPE, FNVATRATE, FNVATAMT, FCWHOUSE, FMREMARK, FCEAFTERR, FTDATETIME, FCPROJ, FNPRICEKE, FNXRATE, FCSTUM, FDDELIVERY, 
                         FCGVPOLICY, FTLASTUPD, FCCREATEAP
FROM ORDERI
where FCORDERH in :orderID
order by FCORDERH,FCSEQ 

--Query NoteCut
SELECT  FCDATASER, FCUDATE, FCUTIME, FCLUPDAPP, FCCORP, FCBRANCH, FCCHILDTYP, FCCHILDH, FCCHILDI, FCMASTERTY, FCMASTERH, FCMASTERI, FNQTY, FNUMQTY, FCCREATETY, FCEAFTERR, FCSELTAG, 
                         FTDATETIME, FIMILLISEC, FCSKID, FTLASTUPD, FTLASTEDIT, FCCREATEAP, FCU1ACC, FCDATAIMP, FCCREATEBY, FCCORRECTB, FTSRCUPD, FCSRCUPD, FMEXTRATAG, FCORGCODE, FCCUACC, FCAPPNAME
FROM    NOTECUT
where FCMASTERH in :orderID