# Generated by Django 4.2.6 on 2023-10-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openpdsdetail',
            name='product_group_id',
        ),
    ]
