# Generated by Django 4.2.6 on 2023-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdserrorlogs',
            name='file_name',
            field=models.UUIDField(verbose_name='File Forecast'),
        ),
    ]
