# Generated by Django 4.2.6 on 2023-10-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_alter_forecast_forecast_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdsheader',
            name='pds_status',
            field=models.CharField(blank=True, choices=[('0', 'In Progress'), ('1', 'Approve'), ('2', 'Success'), ('3', 'Reject')], default='0', max_length=1, null=True, verbose_name='PDS Status'),
        ),
    ]
