# Generated by Django 4.2.6 on 2023-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_vcst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CORP',
            fields=[
                ('FCSKID', models.CharField(db_column='FCSKID', editable=False, max_length=8, primary_key=True, serialize=False)),
                ('FCCODE', models.CharField(db_column='FCCODE', max_length=30)),
                ('FCNAME', models.CharField(db_column='FCNAME', max_length=30)),
            ],
            options={
                'db_table': 'CORP',
            },
        ),
    ]
