# Generated by Django 4.2.6 on 2023-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_vcst', '0002_corp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderh',
            name='FCISPDPART',
            field=models.CharField(blank=True, db_column='FCISPDPART', max_length=1, null=True),
        ),
    ]
