# Generated by Django 4.2.6 on 2023-10-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_vcst', '0004_alter_orderh_fcispdpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderh',
            name='FNVATRATE',
            field=models.FloatField(blank=True, db_column='FNVATRATE', default='7.0', null=True),
        ),
        migrations.AlterField(
            model_name='orderi',
            name='FNVATRATE',
            field=models.FloatField(blank=True, db_column='FNVATRATE', default='7.0', null=True),
        ),
        migrations.AlterField(
            model_name='orderi',
            name='FNXRATE',
            field=models.FloatField(blank=True, db_column='FNXRATE', default='1.0', null=True),
        ),
    ]
