# Generated by Django 4.2.6 on 2023-10-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_pds', '0001_initial'),
        ('forecasts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdsheader',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supplier', verbose_name='Supplier ID'),
        ),
        migrations.AddField(
            model_name='pdsdetail',
            name='forecast_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecastdetail', verbose_name='PDS Detail'),
        ),
        migrations.AddField(
            model_name='pdsdetail',
            name='pds_header_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='open_pds.pdsheader', verbose_name='PDS ID'),
        ),
    ]
