# Generated by Django 4.2.6 on 2023-10-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_pds', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdsdetail',
            options={'ordering': ('seq', 'forecast_detail_id', 'created_at', 'updated_at'), 'permissions': [('create_purchase_order', 'เปิด PO'), ('edit_purchase_qty_price', 'แก้ไขจำนวน/ราคา')], 'verbose_name': 'PDSDetail', 'verbose_name_plural': 'PDS Detail'},
        ),
    ]
