# Generated by Django 4.2.6 on 2023-10-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('code', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
    ]
